name: ftcp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.13
  - pip
  - pip:
    - pip==21.3.1
    - numpy==1.18.5
    - scipy==1.5.4
    - pandas==1.1.5
    - scikit-learn==0.24.2
    - matplotlib==3.3.4
    - tensorflow==1.15.5
    - tensorboard==1.15.0
    - ase==3.22.1
    - pymatgen==2019.12.22
    - matminer==0.6.2
    - keras==2.3.1
    - seaborn==0.11.2
    - plotly==5.17.0
    - spglib==2.0.2
    - tqdm==4.64.1
