name: crystallm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.24.2
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - pymatgen=2023.3.23
  - matminer=0.9.0
  - omegaconf=2.3.0
  - pyyaml=6.0.1
  - smact=2.5.5
  - tqdm=4.65.0
  - pyzmq=25.1.1
